//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klod.Data.PersistenceService.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PersistenceServiceConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static PersistenceServiceConfiguration defaultInstance = ((PersistenceServiceConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PersistenceServiceConfiguration())));
        
        public static PersistenceServiceConfiguration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("type")]
        public string CommandTypeAttribute {
            get {
                return ((string)(this["CommandTypeAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name")]
        public string ParameterNameAttribute {
            get {
                return ((string)(this["ParameterNameAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("property")]
        public string ParameterPropertyAttribute {
            get {
                return ((string)(this["ParameterPropertyAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("class")]
        public string ParameterClassAttribute {
            get {
                return ((string)(this["ParameterClassAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("type")]
        public string ParameterTypeAttribute {
            get {
                return ((string)(this["ParameterTypeAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("direction")]
        public string ParameterDirectionAttribute {
            get {
                return ((string)(this["ParameterDirectionAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("returnTable")]
        public string CommandReturnTableElement {
            get {
                return ((string)(this["CommandReturnTableElement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name")]
        public string ReturnTableNameAttribute {
            get {
                return ((string)(this["ReturnTableNameAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("property")]
        public string ReturnTableColumnPropertyAttribute {
            get {
                return ((string)(this["ReturnTableColumnPropertyAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("map")]
        public string MapElement {
            get {
                return ((string)(this["MapElement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("class")]
        public string MapClassAttribute {
            get {
                return ((string)(this["MapClassAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("type")]
        public string MapTypeAttribute {
            get {
                return ((string)(this["MapTypeAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("storage")]
        public string MapStorageAttribute {
            get {
                return ((string)(this["MapStorageAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("storageType")]
        public string MapStorageTypeAttribute {
            get {
                return ((string)(this["MapStorageTypeAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("commands")]
        public string CommandsElement {
            get {
                return ((string)(this["CommandsElement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mappings.xml")]
        public string MappingsFileAddress {
            get {
                return ((string)(this["MappingsFileAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("use")]
        public string ParameterUseAttribute {
            get {
                return ((string)(this["ParameterUseAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("version")]
        public string VersionColumnName {
            get {
                return ((string)(this["VersionColumnName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inuse")]
        public string InUseColumnName {
            get {
                return ((string)(this["InUseColumnName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The record has been changed since your last retrieval.")]
        public string OptimisticConcurrencyErrorMessage {
            get {
                return ((string)(this["OptimisticConcurrencyErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The record is lock by another user.")]
        public string PessimisticConcurrencyErrorMessage {
            get {
                return ((string)(this["PessimisticConcurrencyErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("version")]
        public string optimisticFieldName {
            get {
                return ((string)(this["optimisticFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InUse")]
        public string pessimisticFieldName {
            get {
                return ((string)(this["pessimisticFieldName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name")]
        public string ReturnTableColumnNameAttribute {
            get {
                return ((string)(this["ReturnTableColumnNameAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Klod.Data.PersistenceService.Relational.SqlServer")]
        public string PersistenceServiceAssembly {
            get {
                return ((string)(this["PersistenceServiceAssembly"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Klod.Data.PersistenceService.Relational.SqlServer.SqlServerPersistenceServer")]
        public string PersistenceServerClass {
            get {
                return ((string)(this["PersistenceServerClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ConcurrencySupport {
            get {
                return ((string)(this["ConcurrencySupport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;initial catalog=DigitalLibraryServer;integrated security=true")]
        public string Connection {
            get {
                return ((string)(this["Connection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("myConnection")]
        public string ConnectionName {
            get {
                return ((string)(this["ConnectionName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;initial catalog=personDb;integrated security=true;MultipleActive" +
            "ResultSet=true")]
        public string myConnection {
            get {
                return ((string)(this["myConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("primaryKey")]
        public string ReturnTableColumnPrimaryKeyAttribute {
            get {
                return ((string)(this["ReturnTableColumnPrimaryKeyAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("command")]
        public string CommandElement {
            get {
                return ((string)(this["CommandElement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("idDataType")]
        public string CommandIdDataTypeAttribute {
            get {
                return ((string)(this["CommandIdDataTypeAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name")]
        public string CommandNameAttribute {
            get {
                return ((string)(this["CommandNameAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("parameters")]
        public string CommandParametersElement {
            get {
                return ((string)(this["CommandParametersElement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int CommandTimeout {
            get {
                return ((int)(this["CommandTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("token")]
        public string ParameterTokenAttribute {
            get {
                return ((string)(this["ParameterTokenAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("z:\\me\\Documents\\Projects\\PersistenceServiceFramework.v4\\Klod.Data.PersistenceServ" +
            "ice.Relational.SqlServer\\bin\\Release\\Klod.Data.PersistenceService.Relational.Sql" +
            "Server.dll")]
        public string PersistenceServiceAssemblyLocation {
            get {
                return ((string)(this["PersistenceServiceAssemblyLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("providerType")]
        public string CommandProviderTypeAttribute {
            get {
                return ((string)(this["CommandProviderTypeAttribute"]));
            }
        }
    }
}
